version: '3'
services:
  php:
    image: 'gitlab.fit.cvut.cz:5050/bi-php/bi-php-docker/php:8.2'
    # for linux 'gitlab.fit.cvut.cz:5050/bi-php/bi-php-docker/php:8.2-linux'
    restart: on-failure
    volumes:
      - .:/var/www/html
    networks:
      - internal

networks:
  internal: